"""Shared fixtures and measurement helpers.

Two conventions the whole suite relies on:

* **No committed binary fixtures.** Everything is generated by
  :mod:`tests.synthetic` from an explicit seed, so the truth is known exactly
  and a failing test can be reproduced from the seed alone.
* **SNR is measured empirically, not read off a propagated map.** Comparing
  two coadds by their own uncertainty maps compares two bookkeeping
  conventions, not two algorithms. :func:`empirical_snr` filters each image
  with *its own* effective PSF and divides by the scatter of the same filter
  evaluated at blank positions in the *same* image. That is the number an
  observer would actually get.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from astrostack.metrics.injection import measure_matched_flux
from astrostack.rng import generator
from astrostack.stack.base import CoaddResult
from tests.synthetic import make_corpus, subtract_known_sky


def blank_positions(
    shape: tuple[int, int],
    sources: np.ndarray,
    n: int = 500,
    margin: int = 20,
    exclusion: float = 14.0,
    seed: int = 987,
) -> np.ndarray:
    """Positions well away from every known source, for noise measurement."""
    h, w = shape
    rng = generator(seed, "blank")
    ys = rng.uniform(margin, h - margin, n)
    xs = rng.uniform(margin, w - margin, n)
    if sources.size:
        d2 = (sources[:, 0][None, :] - ys[:, None]) ** 2 + (sources[:, 1][None, :] - xs[:, None]) ** 2
        keep = d2.min(axis=1) > exclusion**2
    else:
        keep = np.ones(ys.shape, dtype=bool)
    return np.column_stack([ys[keep], xs[keep]])


def empirical_snr(
    result: CoaddResult,
    positions: np.ndarray,
    noise_result: CoaddResult | None = None,
    seed: int = 987,
) -> float:
    """Median matched-filter SNR of ``positions``, with noise measured, not assumed.

    The filter is the coadd's *own* effective PSF, so two coadds with
    different PSFs are compared fairly. The noise is the scatter of the same
    filter at blank positions.

    ``noise_result`` should be an **identically processed source-free stack**.
    Measuring the scatter inside the science image itself would be
    confusion-limited: the faint end of a realistic luminosity function puts
    flux almost everywhere, that flux is real, and it does not average down
    with N — so a self-measured noise floor would make ``sqrt(N)`` scaling
    look like it saturates when in fact the noise is still falling.
    """
    if result.psf is None:
        raise ValueError("empirical_snr needs the coadd's effective PSF")
    noise_image = (noise_result or result).image
    if noise_result is not None and noise_result.image.shape != result.image.shape:
        raise ValueError("noise reference must share the science image's grid")
    blanks = blank_positions(noise_image.shape, positions if noise_result is None else np.empty((0, 2)), seed=seed)
    signal = measure_matched_flux(result.image, result.psf, positions, 1.0)
    noise = measure_matched_flux(noise_image, result.psf, blanks, 1.0)
    scatter = float(np.nanstd(noise))
    if scatter <= 0:
        raise ValueError("degenerate noise measurement")
    return float(np.nanmedian(signal)) / scatter


def _empty_twin(**kwargs) -> list:
    """A source-free corpus with the same noise properties, for noise measurement."""
    twin = make_corpus(empty=True, **kwargs)
    return subtract_known_sky(twin)


_HOMOGENEOUS = dict(
    n_frames=8, shape=(160, 160), n_stars=25, seed=101,
    fwhm_pixels=3.0, sky_level=200.0, dither_pixels=0.0,
)  # fmt: skip

_HETEROGENEOUS = dict(
    n_frames=8, shape=(160, 160), n_stars=25, seed=202,
    fwhm_pixels=[2.0] * 4 + [6.0] * 4,
    sky_level=[800.0] * 4 + [200.0] * 4,
    dither_pixels=0.0,
)  # fmt: skip


@pytest.fixture(scope="session")
def homogeneous_corpus():
    """8 identical-quality frames, sky removed, plus a source-free twin."""
    field = make_corpus(**_HOMOGENEOUS)
    return field, subtract_known_sky(field), _empty_twin(**_HOMOGENEOUS)


@pytest.fixture(scope="session")
def heterogeneous_corpus():
    """8 frames of unequal quality, with seeing anti-correlated with sky.

    Four sharp frames under a bright sky, four blurry frames under a dark sky.
    This is the regime the Zackay-Ofek argument is about: a scalar
    inverse-variance weight picks the *wrong* frames, because the frames with
    the lowest noise are the ones whose PSF spreads the signal furthest.
    """
    field = make_corpus(**_HETEROGENEOUS)
    return field, subtract_known_sky(field), _empty_twin(**_HETEROGENEOUS)


@pytest.fixture(scope="session")
def dithered_corpus():
    """6 frames with real sub-pixel dither and real WCS offsets."""
    field = make_corpus(
        n_frames=6, shape=(128, 128), n_stars=20, seed=303,
        fwhm_pixels=3.0, sky_level=200.0, dither_pixels=1.5,
    )  # fmt: skip
    return field, subtract_known_sky(field)


@pytest.fixture(scope="session")
def noiseless_corpus():
    """6 noiseless dithered frames — for flux-conservation measurements."""
    field = make_corpus(
        n_frames=6, shape=(128, 128), n_stars=15, seed=404,
        fwhm_pixels=3.0, sky_level=0.0, dither_pixels=1.5, add_noise=False,
        read_noise=0.0,
    )  # fmt: skip
    return field, field.frames
