"""El OpenAPI del backend y los tipos del frontend no pueden divergir.

Regla dura 7 de `CLAUDE.md`: los tipos del frontend se **generan** del OpenAPI.
Este test lo comprueba de la única forma que vale: regenerando y comparando.

Cuando falla, la salida dice el comando exacto para arreglarlo. No se arregla
editando `api.gen.ts` a mano — se arregla en el contrato, y luego se regenera.

    backend/.venv/bin/pytest tests/contract -q
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path
from typing import Any

import pytest

from tests.conftest import FRONTEND, REPO_ROOT

pytestmark = pytest.mark.contract

GENERATED = FRONTEND / "app" / "types" / "api.gen.ts"
DOMAIN = FRONTEND / "app" / "types" / "domain.ts"

REGEN_HINT = (
    "Los tipos del frontend no coinciden con el OpenAPI del backend.\n"
    "Regenéralos (con el backend en marcha) y ajusta lo que rompa:\n"
    "    cd frontend && pnpm run gen:api && pnpm typecheck\n"
    "Nunca edites app/types/api.gen.ts a mano (CLAUDE.md, regla dura 7)."
)


def _pnpm(*args: str, timeout: int = 300) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["pnpm", *args],
        cwd=str(FRONTEND),
        capture_output=True,
        text=True,
        check=False,
        timeout=timeout,
    )


def _normalize(text: str) -> str:
    """Quita lo que cambia entre generaciones sin cambiar el contrato."""
    # La cabecera "auto-generated" y los saltos de línea de Windows.
    text = text.replace("\r\n", "\n")
    text = re.sub(r"^/\*\*.*?\*/\n", "", text, count=1, flags=re.DOTALL)
    return text.strip()


@pytest.fixture(scope="module")
def regenerated(api_base: str, tmp_path_factory: pytest.TempPathFactory) -> str:
    """Los tipos tal como los generaría `pnpm run gen:api` ahora mismo."""
    out = tmp_path_factory.mktemp("apigen") / "api.gen.ts"
    proc = _pnpm(
        "exec",
        "openapi-typescript",
        f"{api_base}/openapi.json",
        "-o",
        str(out),
    )
    if proc.returncode != 0:
        pytest.fail(f"openapi-typescript falló:\n{proc.stdout}\n{proc.stderr}")
    return out.read_text(encoding="utf-8")


# --------------------------------------------------------------------------- #
def test_los_tipos_del_frontend_estan_generados_del_openapi_vivo(regenerated: str) -> None:
    """`api.gen.ts` es byte a byte lo que produce el generador. Sin excepciones.

    Este es el test que habría cazado que `api.gen.ts` era un placeholder
    escrito a mano contra un contrato imaginado.
    """
    committed = GENERATED.read_text(encoding="utf-8")
    assert _normalize(committed) == _normalize(regenerated), REGEN_HINT


def test_api_gen_no_lleva_marcas_de_haber_sido_escrito_a_mano() -> None:
    """Un fichero generado no dice 'PLACEHOLDER' ni 'NO EDITAR A MANO'."""
    committed = GENERATED.read_text(encoding="utf-8")
    head = committed[:2000].upper()
    for marker in ("PLACEHOLDER", "STAND-IN", "ESCRITO A MANO", "A MANO"):
        assert marker not in head, (
            f"`api.gen.ts` contiene {marker!r} en su cabecera: sigue siendo un "
            f"fichero escrito a mano.\n{REGEN_HINT}"
        )
    assert "auto-generated by openapi-typescript" in committed[:500], (
        f"`api.gen.ts` no lleva la cabecera del generador.\n{REGEN_HINT}"
    )


def test_domain_ts_solo_declara_alias(openapi: dict[str, Any]) -> None:
    """`domain.ts` traduce nombres; no inventa formas.

    Si alguien declara ahí una interfaz con campos, ha escrito un tipo de red a
    mano por la puerta de atrás. Se permite exactamente una excepción, marcada
    y justificada: el evento del SSE, que FastAPI no describe en el OpenAPI.
    """
    source = DOMAIN.read_text(encoding="utf-8")
    interfaces = re.findall(r"^export interface (\w+)", source, flags=re.MULTILINE)
    assert set(interfaces) <= {"ReconstructionEvent"}, (
        f"`domain.ts` declara formas propias: {interfaces}. Solo puede declarar "
        "alias sobre `components['schemas']`; la única excepción admitida es "
        "`ReconstructionEvent` (SSE, no descrito en el OpenAPI)."
    )


def test_todos_los_alias_de_domain_existen_en_el_schema(openapi: dict[str, Any]) -> None:
    """Cada `S['X']` de `domain.ts` apunta a un schema que el backend publica.

    Falla con la lista de los que faltan, que es lo que hay que arreglar.
    """
    source = DOMAIN.read_text(encoding="utf-8")
    referenced = set(re.findall(r"S\['([^']+)'\]", source))
    published = set(openapi["components"]["schemas"])
    missing = sorted(referenced - published)
    assert not missing, (
        f"`domain.ts` referencia schemas que el backend no publica: {missing}.\n"
        f"Publicados: {sorted(published)}"
    )


def test_el_openapi_declara_problem_json_como_tipo_de_error(openapi: dict[str, Any]) -> None:
    """RFC 9457 está en el contrato, no solo en la implementación."""
    assert "ProblemDetail" in openapi["components"]["schemas"], (
        "El OpenAPI no declara `ProblemDetail`: el frontend no puede tipar los errores."
    )
    problem = openapi["components"]["schemas"]["ProblemDetail"]
    assert {"type", "title", "status", "detail"} <= set(problem["properties"])


def test_el_frontend_typechequea_contra_los_tipos_generados() -> None:
    """La prueba de fuego: `pnpm typecheck` con el `api.gen.ts` del repo.

    Es lento pero es el único test que demuestra que el frontend habla el
    contrato real y no uno imaginado.
    """
    proc = _pnpm("typecheck", timeout=900)
    assert proc.returncode == 0, (
        f"`pnpm typecheck` falla contra los tipos generados:\n{proc.stdout}\n{proc.stderr}"
    )


@pytest.mark.parametrize(
    "route",
    [
        "/healthz",
        "/readyz",
        "/stats",
        "/licenses",
        "/photos",
        "/photos/uploads",
        "/objects",
        "/reconstructions",
        "/reconstructions/preview",
        "/licenses/resolve",
    ],
)
def test_las_rutas_de_docs_api_existen_en_el_openapi(openapi: dict[str, Any], route: str) -> None:
    """`docs/api.md` es el contrato; el OpenAPI tiene que contenerlo."""
    prefix = "/api/v1"
    paths = set(openapi["paths"])
    assert f"{prefix}{route}" in paths, (
        f"`docs/api.md` documenta {route} pero el OpenAPI no lo publica.\n"
        f"Rutas publicadas: {sorted(paths)}"
    )
